version: '3.9'

services:

  postgres:
    container_name: postgres-openmusic
    image: postgres:9.6.21-alpine
    restart: always
    environment:
      POSTGRES_USER: openmusicadmin
      POSTGRES_PASSWORD: openmusicadmin
      POSTGRES_DB: openmusicdb
    ports:
      - 5432:5432
    volumes:
      - ./.postgres-data:/var/lib/postgresql/data
    networks:
      - openmusic_network

networks:
  openmusic_network:
    name: openmusic_network